### Create workspace
POST http://localhost:3000/api/entities/workspaces/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./workspace.json


### Create Postgres connection
POST http://localhost:3000/api/entities/dataSources/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./pgsql_connection.json


### Get semantic model
GET http://localhost:3000/api/layout/workspaces/insurance-demo/logicalModel/
Content-Type: application/json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz


### Publish semantic model
PUT http://localhost:3000/api/layout/workspaces/insurance-demo/logicalModel/
Content-Type: application/json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./ldm.json


### Get measures
GET http://localhost:3000/api/entities/workspaces/insurance-demo/metrics/
Content-Type: application/json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

### Create premium revenue measure
POST http://localhost:3000/api/entities/workspaces/insurance-demo/metrics/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./measure_premium_revenue.json

### Create claim amount measure
POST http://localhost:3000/api/entities/workspaces/insurance-demo/metrics/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./measure_claim_amount.json

### Create total premium revenue measure
POST http://localhost:3000/api/entities/workspaces/insurance-demo/metrics/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./measure_total_premium_revenue.json

### Create total claim amount measure
POST http://localhost:3000/api/entities/workspaces/insurance-demo/metrics/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./measure_total_claim_amount.json

### Create analytics model objects
PUT http://localhost:3000/api/layout/workspaces/insurance-demo/analyticsModel/
Content-Type: application/json
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

< ./analytics_model.json